### ISSUE TITLE
I find that you reproduced CheroeMaster, will you release the code?

### ISSUE THREAD

**Issue by hu394854434** [li-ronghui/FineDance#19]
Nice work! I follow this cheroegraph for a while, besides your work, CheoeMaster seems a nice work too.

**Comment by li-ronghui** [comment]
Hi, ChoreoMaster is the work of other research teams. The code we reproduced cannot guarantee the effect of the original paper, so we have no such plan. Actually, we found that such methods struggle to achieve fine-grained beat alignment with music and dance on general datasets, so we did not pursue further research in this direction.
