### ISSUE TITLE
ChoreoMaster 问题

### ISSUE THREAD

**Issue by MingCongSu** [li-ronghui/FineDance#7]
你好，感谢你们分享这个杰出的作品和开源代码。

请问是否有计画公开ChoreoMaster的再现代码和权重档，这将会对这项研究带来很大的帮助。

感激不尽

**Comment by li-ronghui** [comment]
Hi, ChoreoMaster is the work of other research teams. The code we reproduce cannot guarantee the effect of the original paper, so we have no such plan.
