### ISSUE TITLE
数据集 genre 与 motion 预览问题

### ISSUE THREAD

**Issue by MingCongSu** [li-ronghui/FineDance#8]
你好，我下载了 finedance.rar 并解压缩，我查看所有 label_json 中的 json 档发现只有以下 16 种类别 (Jazz 和 jazz 重复了) :

![image](https://github.com/li-ronghui/FineDance/assets/113020932/4efcd915-db9d-42f2-87f5-35874eee577c)

1. 请问是否会有更多资料释出?

2. 另外请问是否有方法能预览数据集中的舞蹈资料，或是有其他可视化工具可以使用?

感谢

**Comment by li-ronghui** [comment]
Thanks for your attention！

We have no plans to release more data in the near future. 
Use the render.py can visualize the dance motion, details in the README.md file in this repo.

**Comment by MingCongSu** [comment]
Thanks for replying.

I thought there would be 22 types. Because the paper describes in the appendix that "FineDance contains 22 dance genres, which fall into 5 coarse categories." And only 8 genres were specifically mentioned in the paper. Did I misunderstand something?
