### ISSUE TITLE
Why use x_start as the target in each timestep of diffusion training?

### ISSUE THREAD

**Issue by shaoguowen** [li-ronghui/FineDance#9]
Hi, I have seen using noise, pre x_noisy or v_prediction, etc. as the training target, but each timestep uses x_start as the training target, which seems a bit strange. Can you explain it or provide relevant articles?

**Comment by li-ronghui** [comment]
Please refer to the following works:
> Human Motion Diffusion Model
> https://guytevet.github.io/mdm-page/ 
> EDGE: Editable Dance Generation From Music
> https://edge-dance.github.io/
I hope this helps you : )
